os_command_py==1.1.0
pandas==1.0.3
geopandas==0.7.0
numpy==1.17.5
geopy==1.22.0
rasterio==1.1.4                
matplotlib==3.2.1                       
os_command_py==1.1.0
geopandas==0.7.0
libpysal==4.2.2
esda==2.2.1
splot==1.1.3
